language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - psql -c 'create database broadcaster' -U postgres
  
before_script:
  - npm install  

script:
  - npm run test

after_success:
  - npm run coveralls