version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:10
        environment:
          POSTGRES_DB: broadcaster
      steps:
      - run:
          name: Install ltree extension for Postgres
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            dockerize -wait tcp://localhost:5432 -timeout 1m
            psql -U circleci -h localhost -p 5432 -c 'create extension ltree'
      - checkout
      
      - run: npm install
      - run: npm run test

      