class Tokelp {
  constructor() {
    this.adminCreatedToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2F0ZWdvcnkiOiJhZG1pbiIsImZpcnN0bmFtZSI6Im1hbnppIiwibGFzdG5hbWUiOiJ0ZWRkeSIsInVzZXJuYW1lIjoidGlubnkiLCJlbWFpbCI6Imsuam9zaHVhODU1QGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiKzI1MDc4OTYxOTQ0MiIsInBhc3N3b3JkIjoiJDJhJDEyJDllY20zY1p1QURPaXlsTmQ3dENzNS5EQWlLRUE5RldTR1ZOVWVJZlppRDdpN1ZlLmhINTdXIiwiY3JlYXRlZERhdGUiOiJUaHUgTm92IDI4IDIwMTkgMDM6NTc6NDggR01UKzAyMDAgKENlbnRyYWwgQWZyaWNhIFRpbWUpIiwibW9kaWZpZWREYXRlIjoibm9uZSIsImlhdCI6MTU3NDkwNjM3MiwiZXhwIjoxNjYxMzA2MzcyfQ.F7HVY_hnSzIwEDdcaeLgFJ-B_jOpQ0VRB4KfV20y5yM';
    this.userCreatedToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY2F0ZWdvcnkiOiJ1c2VyIiwiZmlyc3RuYW1lIjoibW9yaWFoIiwibGFzdG5hbWUiOiJqZXNzaWNhIiwidXNlcm5hbWUiOiJqZXNzeSIsImVtYWlsIjoiamVzc3lAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIrMjUwNzg5NjAwMDAwIiwicGFzc3dvcmQiOiIkMmEkMTIkVlppNHZRaE5iMmphUkVjWTNBSnBzdS54YmRONy5PRWdiLlNJdHIvZHpPQWRiVWlyMWZ4WmkiLCJjcmVhdGVkRGF0ZSI6IlRodSBOb3YgMjggMjAxOSAwNDoyMjoyNyBHTVQrMDIwMCAoQ2VudHJhbCBBZnJpY2EgVGltZSkiLCJtb2RpZmllZERhdGUiOiJub25lIiwiaWF0IjoxNTc0OTA3NzQ3LCJleHAiOjE2NjEzMDc3NDd9.Os74BSVoKhZ5hFc6yAUgrUf2uCFuN_yz1Z1mR_dXslM';
  }
}

const exptokelp = new Tokelp();
export default exptokelp;
